#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu May 30 11:52:56 2019

@author: pgcseismolab
"""

#%%

import pandas as pd

#%%

#cat = pd.read_csv('~/Documents/chet/dbs/201804-201811', )
input_path = '~/Documents/chet/dbs/201804-201811/'

left = pd.read_csv(input_path + 'db.origin', header=None, delim_whitespace=True,
                            usecols=[0,1,2,3,4,7,8,20], names=['lat','lon','depth','time','orid','nassoc','ndef','ml'])
right = pd.read_csv(input_path + 'db.origerr', delim_whitespace=True, header=None, 
                             usecols = [0,11,12,13,14,15], names=['orid','sdobs','smajax','sminax','strike','sdepth'])

#%%

cat = pd.merge(left, right, on='orid')

#%%

err = cat[cat.smajax > 10]

print(list(err.orid))

#%%

good = cat[cat.smajax <= 10]

#%%

good.to_csv(input_path + 'merged.csv')